//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VMISP.Mis
{
    public partial class frmMiscCheckerView
    {
        /// <summary>
        /// lblRNo control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblRNo;

        /// <summary>
        /// spanStatus control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl spanStatus;

        /// <summary>
        /// lblStatus control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblStatus;

        /// <summary>
        /// lblMaker control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblMaker;

        /// <summary>
        /// lblMakerDate control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblMakerDate;

        /// <summary>
        /// txtRNo control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtRNo;

        /// <summary>
        /// txtCompRecDate control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtCompRecDate;

        /// <summary>
        /// txtCircleOffice control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtCircleOffice;

        /// <summary>
        /// txtBRComplaint control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtBRComplaint;

        /// <summary>
        /// txtCompNo control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtCompNo;

        /// <summary>
        /// txtClosureDate control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtClosureDate;

        /// <summary>
        /// txtAccused control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtAccused;

        /// <summary>
        /// txtAllegations control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtAllegations;

        /// <summary>
        /// txtAmount control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtAmount;

        /// <summary>
        /// txtNPADate control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtNPADate;

        /// <summary>
        /// txtFinalAction control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtFinalAction;

        /// <summary>
        /// txtSource control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtSource;

        /// <summary>
        /// txtZone control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtZone;

        /// <summary>
        /// txtSourceDate control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtSourceDate;

        /// <summary>
        /// txtSourceRef control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtSourceRef;

        /// <summary>
        /// txtAccountName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtAccountName;

        /// <summary>
        /// txtClose control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtClose;

        /// <summary>
        /// txtDateForINVReport control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtDateForINVReport;

        /// <summary>
        /// txtDesignation control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtDesignation;

        /// <summary>
        /// txtNatureComp control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtNatureComp;

        /// <summary>
        /// txtInvestigationDate control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtInvestigationDate;

        /// <summary>
        /// txtType control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtType;

        /// <summary>
        /// txtStatusCode control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtStatusCode;

        /// <summary>
        /// txtNature control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtNature;

        /// <summary>
        /// txtRessonsForClosure control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtRessonsForClosure;

        /// <summary>
        /// txtLetterSentDate control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtLetterSentDate;

        /// <summary>
        /// txtLetterSentTo control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtLetterSentTo;

        /// <summary>
        /// txtReminderDate control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtReminderDate;

        /// <summary>
        /// txtReplyReceivedDate control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtReplyReceivedDate;

        /// <summary>
        /// txtBankName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtBankName;

        /// <summary>
        /// txtPFNumber control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtPFNumber;

        /// <summary>
        /// txtZoneNew control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtZoneNew;

        /// <summary>
        /// txtCircleNew control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtCircleNew;

        /// <summary>
        /// txtZoneType control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtZoneType;

        /// <summary>
        /// txtZOCM control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtZOCM;

        /// <summary>
        /// txtStatus control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtStatus;

        /// <summary>
        /// txtDeskUserRemarks control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtDeskUserRemarks;

        /// <summary>
        /// pnlDecision control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlDecision;

        /// <summary>
        /// pnlVerifyNote control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlVerifyNote;

        /// <summary>
        /// txtCheckerRemarks control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtCheckerRemarks;

        /// <summary>
        /// lnkBack control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink lnkBack;

        /// <summary>
        /// lblMsg control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblMsg;

        /// <summary>
        /// pnlActions control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlActions;

        /// <summary>
        /// btnReject control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnReject;

        /// <summary>
        /// btnPushBack control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnPushBack;

        /// <summary>
        /// btnAccept control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnAccept;
    }
}
