/*
    Vigilance Maker-Checker
    =================================================================================
    Database : VigilanceMISDB
    Requires : 2026-07-27_CaseApproval_Central_MakerChecker_Foundation.sql

    Puts the VIGILANCE module on the central CASE_APPROVAL registry, following the
    recipe in Docs/VMIS_IAC_MakerChecker_Implementation.md sec 9.

    No column is added to VIGILANCE or VIGILANCE_HISTORY. That matters more here than
    anywhere else: the two tables are 171 columns each and spVigilance_Update,
    spVigilanceUser_Update and spVigilanceExcel_Import all copy history with
    INSERT INTO VIGILANCE_HISTORY SELECT * FROM VIGILANCE, which only works while both
    tables stay in exact ordinal alignment.

    Changes
    -------
    0. Registry  : VIGILANCE added to WORKFLOW_MODULE (key CODE, ref RNO, zone NEWZONE).
    1. Backfill  : existing VIGILANCE rows are grandfathered as Approved (see note below).
    2. spVigilance_Update
         insert -> registers the record as Pending and logs SUBMITTED
         update -> blocked when Pending or Rejected; re-queued to Pending (+ RESUBMITTED)
                   when the prior status was Approved or Changes Requested
         both   -> Zone (New) is now mandatory for a maker, because the zone is what
                   routes the record to a checker. Without it the record would sit
                   Pending forever, invisible to every inbox and locked from editing.
         Both entry pages (Mis/frmVigilance.aspx and Mis/Vigilance.aspx) call this one
         procedure, so enforcing here covers both.
    3. spVigilance_View : LIST / SEARCH / GET now return APPROVALSTATUS,
                          APPROVALSTATUSTEXT and CHECKERREMARKS.
    4. spVigilanceUser_Update : closes the bypass -- changing Basic Pay / DA_CO-ZO-HO /
                          Register / Penalty Proceeding on an approved record now sends
                          it back to the checker instead of leaving it approved and
                          unverified.

    No procedure signature changes, so every existing C# call site keeps working.
    New @o_ERRCODE values on spVigilance_Update: 4 = zone missing, 5 = record locked.

    Backfill note
    -------------
    Step 1 marks every pre-existing VIGILANCE row Approved, on the basis that those
    records predate the control and were never anyone's to check. Flipping them to 'P'
    instead would flood the checker inbox and lock every existing record from editing.
    Change the literal in step 1 if the business wants the opposite.

    Safe to re-run.
*/

SET NOCOUNT ON;
GO

-------------------------------------------------------------------------------------------------
-- 0. Register VIGILANCE in the module registry
--
--    KeyColumn  CODE    -> CASE_APPROVAL.RecordCode  (int identity surrogate)
--    RefColumn  RNO     -> CASE_APPROVAL.RecordRef   (the R Number a user sees)
--    ZoneColumn NEWZONE -> CASE_APPROVAL.ZoneSolID   (routes the record to a checker)
-------------------------------------------------------------------------------------------------
MERGE dbo.WORKFLOW_MODULE AS T
USING (VALUES
        ('VIGILANCE', 'Vigilance', 'VIGILANCE', 'CODE', 'RNO', 'NEWZONE', '~/Mis/frmVigilanceCheckerView.aspx', 1)
      ) AS S (ModuleCode, ModuleName, TableName, KeyColumn, RefColumn, ZoneColumn, ViewPage, IsActive)
   ON T.ModuleCode = S.ModuleCode
WHEN MATCHED THEN UPDATE SET
        T.ModuleName = S.ModuleName,
        T.TableName  = S.TableName,
        T.KeyColumn  = S.KeyColumn,
        T.RefColumn  = S.RefColumn,
        T.ZoneColumn = S.ZoneColumn,
        T.ViewPage   = S.ViewPage,
        T.IsActive   = S.IsActive
WHEN NOT MATCHED THEN
    INSERT (ModuleCode, ModuleName, TableName, KeyColumn, RefColumn, ZoneColumn, ViewPage, IsActive)
    VALUES (S.ModuleCode, S.ModuleName, S.TableName, S.KeyColumn, S.RefColumn, S.ZoneColumn, S.ViewPage, S.IsActive);
GO

-------------------------------------------------------------------------------------------------
-- 1. Backfill: grandfather pre-existing VIGILANCE records
-------------------------------------------------------------------------------------------------
INSERT INTO dbo.CASE_APPROVAL
    (ModuleCode, RecordCode, RecordRef, ZoneSolID, ApprovalStatus, MakerUser, MakerDate, CheckerUser, CheckerDate, CheckerRemarks)
SELECT  'VIGILANCE',
        V.CODE,
        V.RNO,
        V.NEWZONE,
        'A',
        ISNULL(V.ADDUSER, 'SYSTEM'),
        ISNULL(V.ADDDATE, GETDATE()),
        'SYSTEM',
        GETDATE(),
        'Pre-existing record grandfathered at maker-checker rollout.'
FROM    dbo.VIGILANCE V
WHERE   V.ACTIVE = 'Y'
  AND   NOT EXISTS (SELECT 1 FROM dbo.CASE_APPROVAL CA
                    WHERE CA.ModuleCode = 'VIGILANCE' AND CA.RecordCode = V.CODE);
GO

INSERT INTO dbo.CASE_APPROVAL_HISTORY (ModuleCode, RecordCode, ActionType, ActionBy, Remarks)
SELECT  'VIGILANCE', CA.RecordCode, 'GRANDFATHERED', 'SYSTEM',
        'Pre-existing record grandfathered at maker-checker rollout.'
FROM    dbo.CASE_APPROVAL CA
WHERE   CA.ModuleCode = 'VIGILANCE'
  AND   CA.CheckerUser = 'SYSTEM'
  AND   NOT EXISTS (SELECT 1 FROM dbo.CASE_APPROVAL_HISTORY H
                    WHERE H.ModuleCode = 'VIGILANCE' AND H.RecordCode = CA.RecordCode
                      AND H.ActionType = 'GRANDFATHERED');
GO

-------------------------------------------------------------------------------------------------
-- 2. dbo.spVigilance_Update
--    (full body below is the complete, current definition -- not a diff)
-------------------------------------------------------------------------------------------------
CREATE OR ALTER PROC [dbo].[spVigilance_Update]
(
	@p_CODE						BIGINT,
	@p_RNO						VARCHAR(50),
	@p_BRCOMPLAINT				VARCHAR(100),
    @p_CIRCLEOFFICE				VARCHAR(100),
    @p_RNO1						VARCHAR(50),
    @p_NAMEOFPARTICULARS		VARCHAR(100),
    @p_NAME						VARCHAR(100),
    @p_PFNO						VARCHAR(50),
    @p_PRESENTPOSTING			VARCHAR(100),
    @p_SOURCE					VARCHAR(50),
    @p_REGISTER					VARCHAR(100),
    @p_ACCOUNTNAME				VARCHAR(100),
    @p_AMOUNT					DECIMAL(19,4),
    @p_FINAL					VARCHAR(100),
    @p_DESIGNATION				VARCHAR(50),
    @p_DREFNO					VARCHAR(50),
    @p_LAPSENATURE				VARCHAR(150),
    @p_REASONSFORINCLUSION		VARCHAR(500),
    @p_DAREFNO					VARCHAR(50),
    @p_DELETIONREASONS			VARCHAR(150),
	@p_US						VARCHAR(100),
	@p_INVOFFICERNAME			VARCHAR(100),
    @p_RECOMMOFCVC				VARCHAR(100),
    @p_CBIRCNO1					VARCHAR(100),
    @p_IRCBIPENDING				VARCHAR(100),
    @p_CBIRECOM					VARCHAR(100),
    @p_POLFIRNO					VARCHAR(100),
    @p_RCSOURCE					VARCHAR(100),
    @p_INVESTIG					VARCHAR(100),
    @p_CVCOMNO					VARCHAR(100),
    @p_CVC2PROPOSED				VARCHAR(100),
    @p_ADV1AWAITED				VARCHAR(100),
    @p_NATUREOFACCOUNT			VARCHAR(100),
    @p_PONAME					VARCHAR(100),
    @p_POCBI					VARCHAR(100),
    @p_DTSHEAR					VARCHAR(100),
    @p_PUNISHMENTPROPOSEDBYDA	VARCHAR(100),
    @p_PENALTY					VARCHAR(100),
    @p_DISPAUTHORITY			VARCHAR(100),
    @p_DISAUTHORITYCIRCLE		VARCHAR(100),
    @p_PREVCASEPUNISHMENT		VARCHAR(100),
    @p_BASICPAY					VARCHAR(100),
    @p_CVOADVICE				VARCHAR(100),
    @p_NAPUNDA					VARCHAR(MAX),
    @p_LODINO					VARCHAR(100),
    @p_LODICASE					VARCHAR(100),			
    @p_CONNECTEDVIGCASE			VARCHAR(100),
    @p_FIELD1					VARCHAR(100),
    @p_2DAPROPOSAL				VARCHAR(100),
    @p_2NDPENDING				VARCHAR(100),
    @p_STATE					VARCHAR(100),
    @p_NATCHSHEET				VARCHAR(100),
    @p_RECOM					VARCHAR(100),
    @p_NOAWARDS					VARCHAR(100),
    @p_PROPOSEDACTIONTOCVC		VARCHAR(100),
    @p_REGINVOK					VARCHAR(100),
    @p_CBIRCNO2					VARCHAR(100),
    @p_EONAME					VARCHAR(100),
    @p_CDINAME					VARCHAR(100),
    @p_ADV2AWT					VARCHAR(100),
    @p_STATUSINBRIEF			VARCHAR(100),
    @p_LODINEW					VARCHAR(100),
    @p_EOCDI					VARCHAR(100),
    @p_DAPROPOSAL				VARCHAR(100),
    @p_ISTPENDING				VARCHAR(100),
    @p_CVO2ADVICE				VARCHAR(100),
    @p_CVCADVICEII				VARCHAR(100),
    @p_STATUS					VARCHAR(MAX),
	@p_HOSTATUS					VARCHAR(250)=NULL,
	@p_STATUSCODE				VARCHAR(50),
	@p_ZONE						VARCHAR(50),
	@p_NATURECASE				VARCHAR(50),
	@p_SCALE					VARCHAR(50),
	@p_CLOSURE					VARCHAR(1),	
	@p_PENALTYTYPE				VARCHAR(100),
	@p_CHK_RNODATE				VARCHAR(1),
	@p_PENALTYPROCEEDINGS		BIGINT,
	@p_LODICODE					VARCHAR(10),
	@p_LODIINCLUSIONREASON		VARCHAR(250),
	@p_LODIDELETIONREASON		VARCHAR(250),
	
	@p_RECDATECOMP				DATETIME=NULL,
    @p_RNODATE					DATETIME=NULL,
    @p_CHARGEDATE				DATETIME=NULL,
    @p_RC1DATE					DATETIME=NULL,
    @p_RETIREMENTDATE			DATETIME=NULL,
    @p_SUSPENSION				DATETIME=NULL,
    @p_RECREPORTDATE			DATETIME=NULL,
    @p_OCCURDATE				DATETIME=NULL,
    @p_OMCVCDATE				DATETIME=NULL,
    @p_FIRDATE					DATETIME=NULL,
    @p_APPPODATE				DATETIME=NULL,
    @p_APPEODATE				DATETIME=NULL,
    @p_LASTRHDATE				DATETIME=NULL,
    @p_FINALDATE				DATETIME=NULL,
    @p_CONENQDATE				DATETIME=NULL,
    @p_BASICDATE				DATETIME=NULL,
    @p_APPCDIDATE				DATETIME=NULL,
    @p_CVO2ADVICEDATE			DATETIME=NULL,
    @p_ADVICESENTTODADATE		DATETIME=NULL,	
    @p_WRITTENBRIEFCODATE		DATETIME=NULL,
    @p_2NDDADATE				DATETIME=NULL,
    @p_DAORDDATE				DATETIME=NULL,
    @p_REGULATDATE				DATETIME=NULL,
    @p_ISTDADATE				DATETIME=NULL,
    @p_REVOCATIONDATE			DATETIME=NULL,
    @p_REVIEWDATE				DATETIME=NULL,
    @p_CLOSUREDATE				DATETIME=NULL,
    @p_CVOADVICEDATE			DATETIME=NULL,	
    @p_REFERTOCVCDATE			DATETIME=NULL,
    @p_RC2DATE					DATETIME=NULL,
    @p_COMMITMENTDATE			DATETIME=NULL,
    @p_CHSHEETFILEDDATE			DATETIME=NULL,
    @p_COREPLYDATE				DATETIME=NULL,
    @p_TARGETDATE				DATETIME=NULL,
    @p_PLACEINPRESENTSCALEDATE	DATETIME=NULL,
    @p_SANCTIONORDERDATE		DATETIME=NULL,
    @p_ERCODATE					DATETIME=NULL,
	@p_CVC2REF					DATETIME=NULL,
    @p_RECCVC2					DATETIME=NULL,
    @p_APPEAL					DATETIME=NULL,
    @p_PRELIMENQ				DATETIME=NULL,
	@p_REGUENQ					DATETIME=NULL,
	@p_WRITTENBRIEFPO			DATETIME=NULL,
	@p_SANCTIONRECIVED			DATETIME=NULL,
	@p_SANCTIONREFUSED			DATETIME=NULL,
	@p_CSOREPDATE				DATETIME=NULL,
	@p_A1CSCVC					DATETIME=NULL,
	@p_A1EOPOCVC				DATETIME=NULL,
	@p_A2FOCVC					DATETIME=NULL,
	
	@p_MODE						CHAR(1),
	@p_USER						VARCHAR(50),
	@p_USERROLE					VARCHAR(50),	
	@p_DESK_USER_REMARKS		VARCHAR(MAX),
	@p_USERIP					VARCHAR(20),		
	@o_EERMSG					VARCHAR(MAX) OUTPUT,
	@o_ERRCODE					INT OUTPUT,
	@p_BANKNAME					VARCHAR(20),

	@p_LETTERSENTTO				VARCHAR(10),
	@p_LETTERSENTDATE			DATETIME=NULL,
	@p_REMINDERDATE				DATETIME=NULL,
	@p_REPLYRECEIVEDDATE		DATETIME=NULL,
	@p_ZONENEW					VARCHAR(10)=NULL,
	@p_CIRCLENEW				VARCHAR(10)=NULL,
	@p_TMSACREFNO				VARCHAR(50)=NULL
)
AS
BEGIN
	DECLARE @STATUS	VARCHAR(MAX),@UPDATESTATUS VARCHAR(MAX);
	DECLARE @OLDAPPROVALSTATUS CHAR(1), @NEWCODE BIGINT;
	SET @o_ERRCODE=0;
	----------------------------------------------------------------------------------------------
	IF(@p_RNO <> '')
		BEGIN
			IF EXISTS (SELECT 1 FROM VIGILANCE WHERE RNO=@p_RNO AND ACTIVE='Y' AND CODE <> @p_CODE)
				BEGIN
					SET @o_ERRCODE=3;
					SET @o_EERMSG=@p_RNO + '- R Number alredy Exists......!';
				END
		END
	IF(@p_USERROLE = 'VMIS_MISUSER')
		BEGIN
			--MAKER-CHECKER: THE ZONE IS WHAT ROUTES A RECORD TO A CHECKER. A RECORD SAVED
			--WITHOUT ONE WOULD SIT PENDING FOREVER, INVISIBLE TO EVERY INBOX AND LOCKED
			--FROM EDITING, SO REFUSE THE SAVE INSTEAD.
			IF(@o_ERRCODE = 0 AND ISNULL(LTRIM(RTRIM(@p_ZONENEW)),'') = '')
				BEGIN
					SET @o_ERRCODE=4;
					SET @o_EERMSG='Zone (New) is mandatory. It decides which checker verifies this record.';
				END

			--MAKER-CHECKER: A RECORD AWAITING VERIFICATION, OR ONE THE CHECKER HAS REJECTED,
			--IS NOT THE MAKER''S TO EDIT. THE GRID ALREADY DISABLES THE BUTTON; THIS BLOCKS
			--A DIRECT POSTBACK OR THE SECOND ENTRY PAGE FROM GETTING PAST IT.
			IF(@o_ERRCODE = 0 AND @p_MODE = 'U')
				BEGIN
					SELECT @OLDAPPROVALSTATUS = ApprovalStatus
					FROM   CASE_APPROVAL
					WHERE  ModuleCode = 'VIGILANCE' AND RecordCode = @p_CODE;

					IF(@OLDAPPROVALSTATUS = 'X')
						BEGIN
							SET @o_ERRCODE=5;
							SET @o_EERMSG='This record has been rejected by the checker and cannot be edited.';
						END
					ELSE IF(@OLDAPPROVALSTATUS = 'P')
						BEGIN
							SET @o_ERRCODE=5;
							SET @o_EERMSG='This record is pending verification and cannot be edited until the checker acts on it.';
						END
				END

			IF(@o_ERRCODE = 0)
				BEGIN
					IF(@p_MODE='I')
						BEGIN
						  BEGIN TRY
							BEGIN TRAN;

							 INSERT INTO VIGILANCE (RNO,BRNAME,CIRCLEOFFICE,RNO1,NAMEOFPARTICULARS,
													NAME,PFNUMBER,PRESENTPOSTING,SOURCE,REGISTER,
													ACCTT_NAME,AMOUNT,FINAL,DESIGNATION,PDREFNO_SUSPNO,
													LAPSENATURE,REASONSFORINCLUSION,DAREFNO,DELETIONREASON,US,
													INVOFFICERNAME,RECOMMOFCVC,CBI_RC_NO1,IR_CBIPENDING,RECOM_CBI,
													POL_FIR_NO,RC_SOURCE,INVESTIG,CVC_OM_NO,CVC_2_PROPOSED,
													ADV_1_AWAITED,NATUREOFACCOUNT,NAME_PO,PO_CBI,REF_CVC_2,
													DTS_HEAR,PUNISHMENTPROPOSEDBY,APPEAL,PENALTY,DISP_AUTHORITY,
													DISAUTHORITYSCIRCLE,PREVCASE_PUNISHMENTS,ADVICECVOI,NA_PUN_DA,
													LODINO,LODICASE,CONNECTED_VIGCASE,FEILD1,DAPROPOSAL_2,
													PENDING_2,STATE,NAT_CHSHEET,COMP_RE,NO_AWARD_S,
													PROPOSEDACTIONTOCVC,REG_INVOK,CBI_RC_NO2,NAME_EO,NAME_CDI,
													PRELIM_ENQ,ADV_2_AWT,REC_CVC_2,REGU_ENQ,STATUS_INBRIEF,
													LODINEW,EOCDI,DAPROPOSAL,ISTPENDING,ADVICECVO2,
													CVCSADVICEII,STATUS,STATUSCODE,BASICPAY,CBI_ZONE,SCALE,NATURECASE,
													PENALTYTYPE,PENALTYPROCEEDING,LODICODE,LODIINCLUSIONREASON,LODIDELETIONREASON,
											
													DATEOFCOMPLAINT,DTRNO,DTCHARGE,DT_RC1,DTOFRETIREMENT,
													DTOFSUSPENSION,DTOFRECREPORT,DTOCCUR,DT_OM_CVC,DT_FIR,
													DT_APP_PO,DT_APP_EO,DTLASTRH,DTFINAL,DT_CON_ENQ,
													DTOFBASICPAY,DT_APP_CDI,DT_CVO_ADVICE_2,DTADVICESENTTODA,DTWRITTENBRIEFCo,
													DT_2ND_DA,DT_ORD_DA,DT_REGULAT,DT_IST_DA,DTOFREVOCATION,
													REVIEWDATE,DATEOFCLOSURE,DT_CVO_ADVICE,DTREFERTOCVC,DT_RC2,
													COMMITMENTDT,DTCHSHEETFILED,DTREPLYCO,TARGETDATE,DTOFPLACEMENTINPRESENTSCALE,
													DTSANCTIONORDER,DT_ERCO,DTWRITTENBRIEFPO,dtSANCTIONRECIVED,dtSANCTIONREFUSED,
													DT_SUB_REP,A1C_CVC,A1E_CVC,A2_CVC,
													ADDUSER,ADDDATE,ADDUSERIP,BANKNAME,
													LETTERSENTTO,LETTERSENTDATE,REMINDERDATE,REPLYRECEIVEDDATE,
													NEWZONE,NEWCIRCLE,TMSAC_REF) 
													
										VALUES (@p_RNO,@p_BRCOMPLAINT,@p_CIRCLEOFFICE,@p_RNO1,@p_NAMEOFPARTICULARS,
												@p_NAME,@p_PFNO,@p_PRESENTPOSTING,@p_SOURCE,@p_REGISTER,
												@p_ACCOUNTNAME,@p_AMOUNT,@p_FINAL,@p_DESIGNATION,@p_DREFNO,
												@p_LAPSENATURE,@p_REASONSFORINCLUSION,@p_DAREFNO,@p_DELETIONREASONS,@p_US,
												@p_INVOFFICERNAME,@p_RECOMMOFCVC,@p_CBIRCNO1,@p_IRCBIPENDING,@p_CBIRECOM,
												@p_POLFIRNO,@p_RCSOURCE,@p_INVESTIG,@p_CVCOMNO,@p_CVC2PROPOSED,
												@p_ADV1AWAITED,@p_NATUREOFACCOUNT,@p_PONAME,@p_POCBI,@p_CVC2REF,
												@p_DTSHEAR,@p_PUNISHMENTPROPOSEDBYDA,@p_APPEAL,@p_PENALTY,@p_DISPAUTHORITY,
												@p_DISAUTHORITYCIRCLE,@p_PREVCASEPUNISHMENT,@p_CVOADVICE,@p_NAPUNDA,
												@p_LODINO,@p_LODICASE,@p_CONNECTEDVIGCASE,@p_FIELD1,@p_2DAPROPOSAL,
												@p_2NDPENDING,@p_STATE,@p_NATCHSHEET,@p_RECOM,@p_NOAWARDS,
												@p_PROPOSEDACTIONTOCVC,@p_REGINVOK,@p_CBIRCNO2,@p_EONAME,@p_CDINAME,
												@p_PRELIMENQ,@p_ADV2AWT,@p_RECCVC2,@p_REGUENQ,@p_STATUSINBRIEF,
												@p_LODINEW,@p_EOCDI,@p_DAPROPOSAL,@p_ISTPENDING,@p_CVO2ADVICE,
												@p_CVCADVICEII,@p_STATUS,@p_STATUSCODE,@p_BASICPAY,@p_ZONE,
												@p_SCALE,@p_NATURECASE,@p_PENALTYTYPE,@p_PENALTYPROCEEDINGS,
												@p_LODICODE,@p_LODIINCLUSIONREASON,@p_LODIDELETIONREASON,
									
												@p_RECDATECOMP,(CASE WHEN(@p_CHK_RNODATE = 'Y') THEN GETDATE() ELSE NULL END),
												@p_CHARGEDATE,@p_RC1DATE,@p_RETIREMENTDATE,
												@p_SUSPENSION,@p_RECREPORTDATE,@p_OCCURDATE,@p_OMCVCDATE,@p_FIRDATE,
												@p_APPPODATE,@p_APPEODATE,@p_LASTRHDATE,@p_FINALDATE,@p_CONENQDATE,
												@p_BASICDATE,@p_APPCDIDATE,@p_CVO2ADVICEDATE,@p_ADVICESENTTODADATE,@p_WRITTENBRIEFCODATE,
												@p_2NDDADATE,@p_DAORDDATE,@p_REGULATDATE,@p_ISTDADATE,@p_REVOCATIONDATE,
												@p_REVIEWDATE,(CASE WHEN(@p_CLOSURE = 'Y') THEN GETDATE() ELSE NULL END),@p_CVOADVICEDATE,@p_REFERTOCVCDATE,@p_RC2DATE,
												@p_COMMITMENTDATE,@p_CHSHEETFILEDDATE,@p_COREPLYDATE,@p_TARGETDATE,@p_PLACEINPRESENTSCALEDATE,
												@p_SANCTIONORDERDATE,@p_ERCODATE,@p_WRITTENBRIEFPO,@p_SANCTIONRECIVED,@p_SANCTIONREFUSED,
												@p_CSOREPDATE,@p_A1CSCVC,@p_A1EOPOCVC,@p_A2FOCVC,
												@p_USER,GETDATE(),@p_USERIP,@p_BANKNAME,
												@p_LETTERSENTTO,@p_LETTERSENTDATE,@p_REMINDERDATE,@p_REPLYRECEIVEDDATE,
												@p_ZONENEW,@p_CIRCLENEW,@p_TMSACREFNO)

							SET @NEWCODE = SCOPE_IDENTITY();

							--MAKER-CHECKER: REGISTER THE NEW RECORD AS PENDING VERIFICATION
							INSERT INTO CASE_APPROVAL
								(ModuleCode, RecordCode, RecordRef, ZoneSolID, ApprovalStatus, MakerUser, MakerDate)
							VALUES
								('VIGILANCE', @NEWCODE, @p_RNO, @p_ZONENEW, 'P', @p_USER, GETDATE());

							INSERT INTO CASE_APPROVAL_HISTORY
								(ModuleCode, RecordCode, ActionType, ActionBy, Remarks, UserRole, UserIP)
							VALUES
								('VIGILANCE', @NEWCODE, 'SUBMITTED', @p_USER, NULL, @p_USERROLE, @p_USERIP);

							COMMIT TRAN;

							SET @o_ERRCODE=1;
							SET @o_EERMSG='Record Saved Sucessfully......!';
						  END TRY
						  BEGIN CATCH
							IF (XACT_STATE() <> 0) ROLLBACK TRAN;
							SET @o_ERRCODE=0;
							SET @o_EERMSG='Could not save the record: ' + ERROR_MESSAGE();
						  END CATCH
						END
	
					ELSE IF(@p_MODE='U')
						BEGIN
						  BEGIN TRY
							BEGIN TRAN;

							--UPDATE TBALE VIGILANCE_HISTORY
							INSERT INTO VIGILANCE_HISTORY SELECT * FROM VIGILANCE WHERE CODE=@p_CODE;
					
							--UPDATE DATA OF VIGILANCE
							UPDATE VIGILANCE SET RNO=@p_RNO,
												 BRNAME=@p_BRCOMPLAINT,
												 CIRCLEOFFICE=@p_CIRCLEOFFICE,
												 RNO1=@p_RNO1,
												 NAMEOFPARTICULARS=@p_NAMEOFPARTICULARS,
												 NAME=@p_NAME,
												 PFNUMBER=@p_PFNO,
												 PRESENTPOSTING=@p_PRESENTPOSTING,
												 SOURCE=@p_SOURCE,
												 REGISTER=@p_REGISTER,
												 ACCTT_NAME=@p_ACCOUNTNAME,
												 AMOUNT=@p_AMOUNT,
												 FINAL=@p_FINAL,
												 DESIGNATION=@p_DESIGNATION,
												 PDREFNO_SUSPNO=@p_DREFNO,
												 LAPSENATURE=@p_LAPSENATURE,
												 REASONSFORINCLUSION=@p_REASONSFORINCLUSION,
												 DAREFNO=@p_DAREFNO,
												 DELETIONREASON=@p_DELETIONREASONS,
												 US=@p_US,
												 BASICPAY=@p_BASICPAY,
												 INVOFFICERNAME=@p_INVOFFICERNAME,
												 RECOMMOFCVC=@p_RECOMMOFCVC,
												 CBI_RC_NO1=@p_CBIRCNO1,
												 IR_CBIPENDING=@p_IRCBIPENDING,
												 RECOM_CBI=@p_CBIRECOM,
												 POL_FIR_NO=@p_POLFIRNO,
												 RC_SOURCE=@p_RCSOURCE,
												 INVESTIG=@p_INVESTIG,
												 CVC_OM_NO=@p_CVCOMNO,
												 CVC_2_PROPOSED=@p_CVC2PROPOSED,
												 ADV_1_AWAITED=@p_ADV1AWAITED,
												 NATUREOFACCOUNT=@p_NATUREOFACCOUNT,
												 NAME_PO=@p_PONAME,
												 PO_CBI=@p_POCBI,
												 DTS_HEAR=@p_DTSHEAR,
												 PUNISHMENTPROPOSEDBY=@p_PUNISHMENTPROPOSEDBYDA,
												 PENALTY=@p_PENALTY,
												 DISP_AUTHORITY=@p_DISPAUTHORITY,
												 DISAUTHORITYSCIRCLE=@p_DISAUTHORITYCIRCLE,
												 PREVCASE_PUNISHMENTS=@p_PREVCASEPUNISHMENT,
												 ADVICECVOI=@p_CVOADVICE,
												 NA_PUN_DA=@p_NAPUNDA,
												 LODINO=@p_LODINO,
												 LODICASE=@p_LODICASE,
												 CONNECTED_VIGCASE=@p_CONNECTEDVIGCASE,
												 FEILD1=@p_FIELD1,
												 DAPROPOSAL_2=@p_2DAPROPOSAL,
												 PENDING_2=@p_2NDPENDING,
												 STATE=@p_STATE,
												 NAT_CHSHEET=@p_NATCHSHEET,
												 COMP_RE=@p_RECOM,
												 NO_AWARD_S=@p_NOAWARDS,
												 PROPOSEDACTIONTOCVC=@p_PROPOSEDACTIONTOCVC,
												 REG_INVOK=@p_REGINVOK,
												 CBI_RC_NO2=@p_CBIRCNO2,
												 NAME_EO=@p_EONAME,
												 NAME_CDI=@p_CDINAME,
												 ADV_2_AWT=@p_ADV2AWT,
												 STATUS_INBRIEF=@p_STATUSINBRIEF,
												 LODINEW=@p_LODINEW,
												 EOCDI=@p_EOCDI,
												 DAPROPOSAL=@p_DAPROPOSAL,
												 ISTPENDING=@p_ISTPENDING,
												 ADVICECVO2=@p_CVO2ADVICE,
												 CVCSADVICEII=@p_CVCADVICEII,
												 STATUS=@p_STATUS,
												 STATUSCODE=@p_STATUSCODE,
												 CBI_ZONE=@p_ZONE,
												 SCALE=@p_SCALE,
												 NATURECASE=@p_NATURECASE,
												 PENALTYTYPE=@p_PENALTYTYPE,
												 PENALTYPROCEEDING=@p_PENALTYPROCEEDINGS,
												 LODICODE=@p_LODICODE,
												 LODIINCLUSIONREASON=@p_LODIINCLUSIONREASON,
												 LODIDELETIONREASON=@p_LODIDELETIONREASON,
										 
												 DATEOFCOMPLAINT=@p_RECDATECOMP,
												 DTRNO=(CASE WHEN(@p_CHK_RNODATE = 'Y') THEN GETDATE() ELSE @p_RNODATE END),
												 DTCHARGE=@p_CHARGEDATE,
												 DT_RC1=@p_RC1DATE,
												 DTOFRETIREMENT=@p_RETIREMENTDATE,
												 DTOFSUSPENSION=@p_SUSPENSION,
												 DTOFRECREPORT=@p_RECREPORTDATE,
												 DTOCCUR=@p_OCCURDATE,
												 DT_OM_CVC=@p_OMCVCDATE,
												 DT_FIR=@p_FIRDATE,
												 DT_APP_PO=@p_APPPODATE,
												 DT_APP_EO=@p_APPEODATE,
												 DTLASTRH=@p_LASTRHDATE,
												 DTFINAL=@p_FINALDATE,
												 DT_CON_ENQ=@p_CONENQDATE,
												 DTOFBASICPAY=@p_BASICDATE,
												 DT_APP_CDI=@p_APPCDIDATE,
												 DT_CVO_ADVICE_2=@p_CVO2ADVICEDATE,
												 DTADVICESENTTODA=@p_ADVICESENTTODADATE,
												 DTWRITTENBRIEFCo=@p_WRITTENBRIEFCODATE,
												 DT_2ND_DA=@p_2NDDADATE,
												 DT_ORD_DA=@p_DAORDDATE,
												 DT_REGULAT=@p_REGULATDATE,
												 DT_IST_DA=@p_ISTDADATE,
												 DTOFREVOCATION=@p_REVOCATIONDATE,
												 REVIEWDATE=@p_REVIEWDATE,
												 DATEOFCLOSURE=(CASE WHEN(@p_CLOSURE = 'Y') THEN GETDATE() ELSE @p_CLOSUREDATE END),
												 DT_CVO_ADVICE=@p_CVOADVICEDATE,
												 DTREFERTOCVC=@p_REFERTOCVCDATE,
												 DT_RC2=@p_RC2DATE,
												 COMMITMENTDT=@p_COMMITMENTDATE,
												 DTCHSHEETFILED=@p_CHSHEETFILEDDATE,
												 DTREPLYCO=@p_COREPLYDATE,
												 TARGETDATE=@p_TARGETDATE,
												 DTOFPLACEMENTINPRESENTSCALE=@p_PLACEINPRESENTSCALEDATE,
												 DTSANCTIONORDER=@p_SANCTIONORDERDATE,
												 DT_ERCO=@p_ERCODATE,
												 REF_CVC_2=@p_CVC2REF,
												 REC_CVC_2=@p_RECCVC2,
												 APPEAL=@p_APPEAL,
												 PRELIM_ENQ=@p_PRELIMENQ,
												 REGU_ENQ=@p_REGUENQ,
												 DTWRITTENBRIEFPO=@p_WRITTENBRIEFPO,
												 dtSANCTIONRECIVED=@p_SANCTIONRECIVED,
												 dtSANCTIONREFUSED=@p_SANCTIONREFUSED,
												 DT_SUB_REP=@p_CSOREPDATE,
												 A1C_CVC=@p_A1CSCVC,
												 A1E_CVC=@p_A1EOPOCVC,
												 A2_CVC=@p_A2FOCVC,
										 
												 MODUSER=@p_USER,
												 MODDATE=GETDATE(),
												 MODUSERIP=@p_USERIP,
												 BANKNAME=@p_BANKNAME,
												 LETTERSENTTO=@p_LETTERSENTTO,
												 LETTERSENTDATE=@p_LETTERSENTDATE,
												 REMINDERDATE=@p_REMINDERDATE,
												 REPLYRECEIVEDDATE=@p_REPLYRECEIVEDDATE,
												 NEWZONE=@p_ZONENEW,
												 NEWCIRCLE=@p_CIRCLENEW,
												 TMSAC_REF = @p_TMSACREFNO				
									WHERE CODE=@p_CODE;

							IF(@OLDAPPROVALSTATUS IS NULL)
								BEGIN
									--A RECORD THAT PREDATES THE ROLLOUT, OR ONE CREATED BY AN IMPORT.
									--ONBOARD IT NOW SO THE EDIT IS VERIFIED.
									INSERT INTO CASE_APPROVAL
										(ModuleCode, RecordCode, RecordRef, ZoneSolID, ApprovalStatus, MakerUser, MakerDate)
									VALUES
										('VIGILANCE', @p_CODE, @p_RNO, @p_ZONENEW, 'P', @p_USER, GETDATE());

									INSERT INTO CASE_APPROVAL_HISTORY
										(ModuleCode, RecordCode, ActionType, ActionBy, Remarks, UserRole, UserIP)
									VALUES
										('VIGILANCE', @p_CODE, 'SUBMITTED', @p_USER, NULL, @p_USERROLE, @p_USERIP);
								END
							ELSE
								BEGIN
									--AN EDIT INVALIDATES A PREVIOUS DECISION, SO SEND THE RECORD BACK
									--TO THE CHECKER'S QUEUE. KEEP THE REFERENCE AND ZONE IN STEP WITH
									--THE CASE ROW SO ROUTING FOLLOWS A ZONE CHANGE.
									UPDATE CASE_APPROVAL
									   SET RecordRef      = @p_RNO,
										   ZoneSolID      = @p_ZONENEW,
										   ApprovalStatus = 'P',
										   MakerUser      = @p_USER,
										   MakerDate      = GETDATE(),
										   CheckerUser    = NULL,
										   CheckerDate    = NULL,
										   CheckerRemarks = NULL
									 WHERE ModuleCode = 'VIGILANCE' AND RecordCode = @p_CODE;

									INSERT INTO CASE_APPROVAL_HISTORY
										(ModuleCode, RecordCode, ActionType, ActionBy, Remarks, UserRole, UserIP)
									VALUES
										('VIGILANCE', @p_CODE, 'RESUBMITTED', @p_USER, NULL, @p_USERROLE, @p_USERIP);
								END

							COMMIT TRAN;

							SET @o_ERRCODE= 2;
							SET @o_EERMSG='Record Updated Sucessfully......!';
						  END TRY
						  BEGIN CATCH
							IF (XACT_STATE() <> 0) ROLLBACK TRAN;
							SET @o_ERRCODE=0;
							SET @o_EERMSG='Could not update the record: ' + ERROR_MESSAGE();
						  END CATCH
						END
						END
					END

			ELSE IF(@p_USERROLE = 'VMIS_DESKUSER')
				BEGIN
					--UPDATE TBALE IAC_HISTORY
					INSERT INTO VIGILANCE_HISTORY SELECT * FROM VIGILANCE WHERE CODE=@p_CODE;

					--SELECT STATUS FROM IAC FOR APPEND STATUS IN CASE OF VMIS_DESKUSER USER
					SELECT @STATUS=ISNULL(STATUS,'') FROM VIGILANCE WHERE CODE=@p_CODE;
					
					SET @UPDATESTATUS = @p_HOSTATUS + ' | ' + @STATUS;
								
					UPDATE VIGILANCE SET STATUS=@UPDATESTATUS,
										 DESK_USER_REMARKS=@p_DESK_USER_REMARKS,
										 DESK_USER_ID=@p_USER,
										 DESK_USER_IP=@p_USERIP,
										 DESK_USER_ADDDATE=GETDATE(),
										 DESK_USER_ROLE=@p_USERROLE										  
					WHERE CODE=@p_CODE;
				    SET @o_ERRCODE= 1;
					SET @o_EERMSG='Dealing Officer Remarks Updated Sucessfully......!' 
				END	
END
GO

-------------------------------------------------------------------------------------------------
-- 3. dbo.spVigilance_View
--    LIST / SEARCH / GET all LEFT JOIN CASE_APPROVAL and return three extra columns.
--    LEFT JOIN, so a record with no approval row still lists, with a NULL status.
-------------------------------------------------------------------------------------------------
CREATE OR ALTER PROC [dbo].[spVigilance_View]
(
	@p_SEARCHNO		VARCHAR(50)=NULL,
	@p_VIEW			VARCHAR(50)=NULL,
	@p_ACCOUNTNAME	VARCHAR(50)=NULL,
	@p_NAME			VARCHAR(50)=NULL,
	@p_CBIRCNO1		VARCHAR(50)=NULL,
	@p_CVCOMNO		VARCHAR(50)=NULL,
	@p_STATUS		VARCHAR(50)=NULL,
	@p_PFNUMBER		VARCHAR(50)=NULL,
	@p_BRANCH		VARCHAR(100)=NULL,
	@p_CIRCLE		VARCHAR(100)=NULL,
	@o_EERMSG		VARCHAR(MAX) OUTPUT,
	@o_ERRCODE		INT OUTPUT
)
AS
BEGIN
	DECLARE @SQL VARCHAR(MAX),@STRCOND VARCHAR(MAX),@ERRORCODE VARCHAR(5);
	--------------------------------------------------------------------------------------
	SET @o_ERRCODE=0;
	SET @STRCOND = 'V.ACTIVE=''Y''';
	---------------------------------------------------------------------------------------------------------------------------------------
	IF(@p_SEARCHNO <> '' AND @p_SEARCHNO IS NOT NULL)
			BEGIN
				SET @STRCOND=@STRCOND+ 'AND RNO LIKE''%'+@p_SEARCHNO+'%''' + CHAR(13);
			END
	IF(@p_ACCOUNTNAME <> '' AND @p_ACCOUNTNAME IS NOT NULL)
			BEGIN
				SET @STRCOND=@STRCOND+ 'AND ACCTT_NAME LIKE''%'+@p_ACCOUNTNAME+'%''' + CHAR(13);
			END
	IF(@p_NAME <> '' AND @p_NAME IS NOT NULL)
			BEGIN
				SET @STRCOND=@STRCOND+ 'AND NAME LIKE''%'+@p_NAME+'%''' + CHAR(13);
			END
	IF(@p_CBIRCNO1 <> '' AND @p_CBIRCNO1 IS NOT NULL)
			BEGIN
				SET @STRCOND=@STRCOND+ 'AND CBI_RC_NO1 LIKE''%'+@p_CBIRCNO1+'%''' + CHAR(13);
			END
	IF(@p_CVCOMNO <> '' AND @p_CVCOMNO IS NOT NULL)
			BEGIN
				SET @STRCOND=@STRCOND+ 'AND CVC_OM_NO LIKE''%'+@p_CVCOMNO+'%''' + CHAR(13);
			END
	IF(@p_STATUS <> '' AND @p_STATUS IS NOT NULL)
			BEGIN
				SET @STRCOND=@STRCOND+ 'AND STATUS LIKE''%'+@p_STATUS+'%''' + CHAR(13);
			END
	IF(@p_PFNUMBER <> '' AND @p_PFNUMBER IS NOT NULL)
			BEGIN
				SET @STRCOND=@STRCOND+ 'AND (PFNUMBER LIKE''%'+@p_PFNUMBER+'%'' OR PFNUMBER_OLD LIKE''%'+@p_PFNUMBER+'%'')' + CHAR(13);
			END
	IF(@p_BRANCH <> '' AND @p_BRANCH IS NOT NULL)
			BEGIN
				SET @STRCOND=@STRCOND+ 'AND BRNAME LIKE''%'+@p_BRANCH+'%''' + CHAR(13);
			END
	IF(@p_CIRCLE <> '' AND @p_CIRCLE IS NOT NULL)
			BEGIN
				SET @STRCOND=@STRCOND+ 'AND CIRCLEOFFICE LIKE''%'+@p_CIRCLE+'%''' + CHAR(13);
			END
	---------------------------------------------------------------------------------------------------------------------------------------
	IF(UPPER(@p_VIEW) = 'LIST')
		BEGIN
		  SELECT TOP 20 CODE,RNO,BRNAME AS BRCOMPLAINT,CIRCLEOFFICE AS CIRCLEOFFICE,RNO1 AS RNO1,
				 NAMEOFPARTICULARS AS NAMEOFPARTICULARS,
			     NAME AS NAME,PFNUMBER AS PFNO,PRESENTPOSTING AS PRESENTPOSTING,
			     SOURCE AS SOURCE,REGISTER AS REGISTER,ACCTT_NAME AS ACCOUNTNAME,
			     ISNULL(AMOUNT,0) AS AMOUNT,FINAL AS FINAL,DESIGNATION AS DESIGNATION,
			     PDREFNO_SUSPNO AS DREFNO,LAPSENATURE AS LAPSENATURE,REASONSFORINCLUSION AS REASONSFORINCLUSION,
			     DAREFNO AS DAREFNO,DELETIONREASON AS DELETIONREASONS,US AS US,
			     INVOFFICERNAME AS INVOFFICERNAME,RECOMMOFCVC AS RECOMMOFCVC,CBI_RC_NO1 AS CBIRCNO1,
			     IR_CBIPENDING AS IRCBIPENDING,RECOM_CBI AS CBIRECOM,POL_FIR_NO AS POLFIRNO,
			     RC_SOURCE AS RCSOURCE,INVESTIG AS INVESTIG,CVC_OM_NO AS CVCOMNO,
			     CVC_2_PROPOSED AS CVC2PROPOSED,ADV_1_AWAITED AS ADV1AWAITED,NATUREOFACCOUNT AS NATUREOFACCOUNT,
			     NAME_PO AS PONAME,PO_CBI AS POCBI,
	             DTS_HEAR AS DTSHEAR,PUNISHMENTPROPOSEDBY AS PUNISHMENTPROPOSEDBYDA,
			     PENALTY AS PENALTY,DISP_AUTHORITY AS DISPAUTHORITY,DISAUTHORITYSCIRCLE AS DISAUTHORITYCIRCLE,
			     PREVCASE_PUNISHMENTS AS PREVCASEPUNISHMENT,ADVICECVOI AS CVOADVICE,NA_PUN_DA AS NAPUNDA,
			     LODINO AS LODINO,LODICASE AS LODICASE,CONNECTED_VIGCASE AS CONNECTEDVIGCASE,
			     FEILD1 AS FIELD1,DAPROPOSAL_2 AS DAPROPOSAL2,PENDING_2 AS PENDING2ND,
			     STATE AS STATE,NAT_CHSHEET AS NATCHSHEET,COMP_RE AS RECOM,
			     NO_AWARD_S AS NOAWARDS,PROPOSEDACTIONTOCVC AS PROPOSEDACTIONTOCVC,REG_INVOK AS REGINVOK,
			     CBI_RC_NO2 AS CBIRCNO2,NAME_EO AS EONAME,NAME_CDI AS CDINAME,
			     ADV_2_AWT AS ADV2AWT,STATUS_INBRIEF AS STATUSINBRIEF,LODINEW AS LODINEW,
			     EOCDI AS EOCDI,DAPROPOSAL AS DAPROPOSAL,ISTPENDING AS ISTPENDING,BASICPAY,
			     ADVICECVO2 AS CVO2ADVICE,CVCSADVICEII AS CVCADVICEII,STATUS,STATUSCODE,'' AS WRITTENBRIEFPO,
			     CBI_ZONE AS ZONE,SCALE,ISNULL(NATURECASE,0) AS NATURE,
			     (CASE WHEN DATEOFCLOSURE IS NULL THEN 'N' ELSE 'Y' END) AS CLOSURE,PENALTYTYPE,
			     (CASE WHEN DTRNO IS NULL THEN 'N' ELSE 'Y' END) AS CHK_RNODATE,PENALTYPROCEEDING,
			     LODICODE,LODIINCLUSIONREASON,LODIDELETIONREASON,
				 
				 CONVERT(VARCHAR,DATEOFCOMPLAINT,103) AS RECDATECOMP,
			     CONVERT(VARCHAR,DTRNO ,103) AS RNODATE,
			     CONVERT(VARCHAR,DTCHARGE ,103) AS CHARGEDATE,
			     CONVERT(VARCHAR,DT_RC1 ,103) AS RC1DATE,
			     CONVERT(VARCHAR,DTOFRETIREMENT ,103) AS RETIREMENTDATE,
			     CONVERT(VARCHAR,DTOFSUSPENSION ,103) AS SUSPENSION,
			     CONVERT(VARCHAR,DTOFRECREPORT ,103) AS RECREPORTDATE,
			     CONVERT(VARCHAR,DTOCCUR ,103) AS OCCURDATE,
			     CONVERT(VARCHAR,DT_OM_CVC ,103) AS OMCVCDATE,
			     CONVERT(VARCHAR,DT_FIR ,103) AS FIRDATE,
			     CONVERT(VARCHAR,DT_APP_PO ,103) AS APPPODATE,
			     CONVERT(VARCHAR,DT_APP_EO ,103) AS APPEODATE,
			     CONVERT(VARCHAR,DTLASTRH,103) AS LASTRHDATE,
			     CONVERT(VARCHAR,DTFINAL ,103) AS FINALDATE,
			     CONVERT(VARCHAR,DT_CON_ENQ ,103) AS CONENQDATE,
		         CONVERT(VARCHAR,DTOFBASICPAY,103)AS BASICDATE,
		         CONVERT(VARCHAR,DT_APP_CDI ,103) AS APPCDIDATE,
		         CONVERT(VARCHAR,DT_CVO_ADVICE_2 ,103) AS CVO2ADVICEDATE,
		         CONVERT(VARCHAR,DTADVICESENTTODA ,103) AS ADVICESENTTODADATE,
		         CONVERT(VARCHAR,DTWRITTENBRIEFCo ,103) AS WRITTENBRIEFCODATE,
			     CONVERT(VARCHAR,DT_2ND_DA ,103) AS DA2NDDATE,
			     CONVERT(VARCHAR,DT_ORD_DA ,103) AS DAORDDATE,
			     CONVERT(VARCHAR,DT_REGULAT ,103) AS REGULATDATE,
			     CONVERT(VARCHAR,DT_IST_DA ,103) AS ISTDADATE,
			     CONVERT(VARCHAR,DTOFREVOCATION ,103) AS REVOCATIONDATE,
			     CONVERT(VARCHAR,REVIEWDATE ,103) AS REVIEWDATE,
			     CONVERT(VARCHAR,DATEOFCLOSURE ,103) AS CLOSUREDATE,
			     CONVERT(VARCHAR,DT_CVO_ADVICE ,103) AS CVOADVICEDATE,
			     CONVERT(VARCHAR,DTREFERTOCVC ,103) AS REFERTOCVCDATE,
			     CONVERT(VARCHAR,DT_RC2 ,103) AS RC2DATE,
			     CONVERT(VARCHAR,COMMITMENTDT ,103) AS COMMITMENTDATE,
			     CONVERT(VARCHAR,DTCHSHEETFILED ,103) AS CHSHEETFILEDDATE,
				 CONVERT(VARCHAR,DTREPLYCO ,103) AS COREPLYDATE,
				 CONVERT(VARCHAR,TARGETDATE ,103) AS TARGETDATE,
				 CONVERT(VARCHAR,DTOFPLACEMENTINPRESENTSCALE ,103) AS PLACEINPRESENTSCALEDATE,
				 CONVERT(VARCHAR,DTSANCTIONORDER ,103) AS SANCTIONORDERDATE,
				 CONVERT(VARCHAR,DT_ERCO ,103) AS ERCODATE,
				 CONVERT(VARCHAR,REF_CVC_2,103) AS CVC2REF,
				 CONVERT(VARCHAR,REC_CVC_2,103) AS RECCVC2,
				 CONVERT(VARCHAR,APPEAL,103) AS APPEAL,
				 CONVERT(VARCHAR,PRELIM_ENQ,103) AS PRELIMENQ,
				 CONVERT(VARCHAR,REGU_ENQ,103) AS REGUENQ,
				 CONVERT(VARCHAR,dtSANCTIONRECIVED,103) AS SANCTIONRECIVED,
				 CONVERT(VARCHAR,dtSANCTIONREFUSED,103) AS SANCTIONREFUSED,
				 CONVERT(VARCHAR,DT_SUB_REP,103) AS CSOREPDATE,
				 CONVERT(VARCHAR,A1C_CVC,103) AS A1CSCVC,
				 CONVERT(VARCHAR,A1E_CVC,103) AS A1EOPOCVC,
				 CONVERT(VARCHAR,A2_CVC,103) AS A2FOCVC,
						   
				 ([dbo].ReverseColumnValue_Function(STATUS,RNO,'VIG')) AS SHORTSTATUS,
				   ADDUSER AS ENTRYBY,ISNULL(CONVERT(VARCHAR(50),ADDDATE,103),'') AS ENTRYDATE,
				   ISNULL(MODUSER,'') AS MODIFYBY,ISNULL(CONVERT(VARCHAR(50),MODDATE,103),'') AS MODIFYDATE ,
				   NEWZONE AS NEWZONE,NEWCIRCLE AS NEWCIRCLE, TMSAC_REF AS TMSACREF,
				   CA.ApprovalStatus AS APPROVALSTATUS,
				   CASE CA.ApprovalStatus
						WHEN 'P' THEN 'Pending Approval'
						WHEN 'A' THEN 'Approved'
						WHEN 'C' THEN 'Changes Requested'
						WHEN 'X' THEN 'Rejected'
				   END AS APPROVALSTATUSTEXT,
				   ISNULL(CA.CheckerRemarks,'') AS CHECKERREMARKS
			FROM VIGILANCE V
				 LEFT JOIN CASE_APPROVAL CA ON CA.ModuleCode='VIGILANCE' AND CA.RecordCode=V.CODE
			WHERE V.ACTIVE='Y' 
			ORDER BY V.ADDDATE DESC;
		END
		
	ELSE IF(UPPER(@p_VIEW) = 'SEARCH')
		BEGIN
			SET @SQL='SELECT TOP 20 CODE,RNO,BRNAME AS BRCOMPLAINT,CIRCLEOFFICE AS CIRCLEOFFICE,RNO1 AS RNO1,
							 NAMEOFPARTICULARS AS NAMEOFPARTICULARS,
							 NAME AS NAME,PFNUMBER AS PFNO,PRESENTPOSTING AS PRESENTPOSTING,
							 SOURCE AS SOURCE,REGISTER AS REGISTER,ACCTT_NAME AS ACCOUNTNAME,
							 ISNULL(AMOUNT,0) AS AMOUNT,FINAL AS FINAL,DESIGNATION AS DESIGNATION,
							 PDREFNO_SUSPNO AS DREFNO,LAPSENATURE AS LAPSENATURE,REASONSFORINCLUSION AS REASONSFORINCLUSION,
							 DAREFNO AS DAREFNO,DELETIONREASON AS DELETIONREASONS,US AS US,
							 INVOFFICERNAME AS INVOFFICERNAME,RECOMMOFCVC AS RECOMMOFCVC,CBI_RC_NO1 AS CBIRCNO1,
							 IR_CBIPENDING AS IRCBIPENDING,RECOM_CBI AS CBIRECOM,POL_FIR_NO AS POLFIRNO,
							 RC_SOURCE AS RCSOURCE,INVESTIG AS INVESTIG,CVC_OM_NO AS CVCOMNO,
							 CVC_2_PROPOSED AS CVC2PROPOSED,ADV_1_AWAITED AS ADV1AWAITED,NATUREOFACCOUNT AS NATUREOFACCOUNT,
							 NAME_PO AS PONAME,PO_CBI AS POCBI,(CASE WHEN DTRNO IS NULL THEN ''N'' ELSE ''Y'' END) AS CHK_RNODATE,
							 DTS_HEAR AS DTSHEAR,PUNISHMENTPROPOSEDBY AS PUNISHMENTPROPOSEDBYDA,
							 PENALTY AS PENALTY,DISP_AUTHORITY AS DISPAUTHORITY,DISAUTHORITYSCIRCLE AS DISAUTHORITYCIRCLE,
							 PREVCASE_PUNISHMENTS AS PREVCASEPUNISHMENT,ADVICECVOI AS CVOADVICE,NA_PUN_DA AS NAPUNDA,
							 LODINO AS LODINO,LODICASE AS LODICASE,CONNECTED_VIGCASE AS CONNECTEDVIGCASE,
							 FEILD1 AS FIELD1,DAPROPOSAL_2 AS DAPROPOSAL2,PENDING_2 AS PENDING2ND,
							 STATE AS STATE,NAT_CHSHEET AS NATCHSHEET,COMP_RE AS RECOM,
							 NO_AWARD_S AS NOAWARDS,PROPOSEDACTIONTOCVC AS PROPOSEDACTIONTOCVC,REG_INVOK AS REGINVOK,
							 CBI_RC_NO2 AS CBIRCNO2,NAME_EO AS EONAME,NAME_CDI AS CDINAME,
							 ADV_2_AWT AS ADV2AWT,STATUS_INBRIEF AS STATUSINBRIEF,LODINEW AS LODINEW,
							 EOCDI AS EOCDI,DAPROPOSAL AS DAPROPOSAL,ISTPENDING AS ISTPENDING,BASICPAY,
							 ADVICECVO2 AS CVO2ADVICE,CVCSADVICEII AS CVCADVICEII,STATUS,STATUSCODE,'''' AS WRITTENBRIEFPO,
							 CBI_ZONE AS ZONE,SCALE,ISNULL(NATURECASE,0) AS NATURE,PENALTYTYPE,
							 (CASE WHEN DATEOFCLOSURE IS NULL THEN ''N'' ELSE ''Y'' END) AS CLOSURE,PENALTYPROCEEDING,
							 LODICODE,LODIINCLUSIONREASON,LODIDELETIONREASON,
				 
							 CONVERT(VARCHAR,DATEOFCOMPLAINT,103) AS RECDATECOMP,
							 CONVERT(VARCHAR,DTRNO ,103) AS RNODATE,
							 CONVERT(VARCHAR,DTCHARGE ,103) AS CHARGEDATE,
							 CONVERT(VARCHAR,DT_RC1 ,103) AS RC1DATE,
							 CONVERT(VARCHAR,DTOFRETIREMENT ,103) AS RETIREMENTDATE,
							 CONVERT(VARCHAR,DTOFSUSPENSION ,103) AS SUSPENSION,
							 CONVERT(VARCHAR,DTOFRECREPORT ,103) AS RECREPORTDATE,
							 CONVERT(VARCHAR,DTOCCUR ,103) AS OCCURDATE,
							 CONVERT(VARCHAR,DT_OM_CVC ,103) AS OMCVCDATE,
							 CONVERT(VARCHAR,DT_FIR ,103) AS FIRDATE,
							 CONVERT(VARCHAR,DT_APP_PO ,103) AS APPPODATE,
							 CONVERT(VARCHAR,DT_APP_EO ,103) AS APPEODATE,
							 CONVERT(VARCHAR,DTLASTRH,103) AS LASTRHDATE,
							 CONVERT(VARCHAR,DTFINAL ,103) AS FINALDATE,
							 CONVERT(VARCHAR,DT_CON_ENQ ,103) AS CONENQDATE,
							 CONVERT(VARCHAR,DTOFBASICPAY,103)AS BASICDATE,
							 CONVERT(VARCHAR,DT_APP_CDI ,103) AS APPCDIDATE,
							 CONVERT(VARCHAR,DT_CVO_ADVICE_2 ,103) AS CVO2ADVICEDATE,
							 CONVERT(VARCHAR,DTADVICESENTTODA ,103) AS ADVICESENTTODADATE,
							 CONVERT(VARCHAR,DTWRITTENBRIEFCo ,103) AS WRITTENBRIEFCODATE,
							 CONVERT(VARCHAR,DT_2ND_DA ,103) AS DA2NDDATE,
							 CONVERT(VARCHAR,DT_ORD_DA ,103) AS DAORDDATE,
							 CONVERT(VARCHAR,DT_REGULAT ,103) AS REGULATDATE,
							 CONVERT(VARCHAR,DT_IST_DA ,103) AS ISTDADATE,
							 CONVERT(VARCHAR,DTOFREVOCATION ,103) AS REVOCATIONDATE,
							 CONVERT(VARCHAR,REVIEWDATE ,103) AS REVIEWDATE,
							 CONVERT(VARCHAR,DATEOFCLOSURE ,103) AS CLOSUREDATE,
							 CONVERT(VARCHAR,DT_CVO_ADVICE ,103) AS CVOADVICEDATE,
							 CONVERT(VARCHAR,DTREFERTOCVC ,103) AS REFERTOCVCDATE,
							 CONVERT(VARCHAR,DT_RC2 ,103) AS RC2DATE,
							 CONVERT(VARCHAR,COMMITMENTDT ,103) AS COMMITMENTDATE,
							 CONVERT(VARCHAR,DTCHSHEETFILED ,103) AS CHSHEETFILEDDATE,
							 CONVERT(VARCHAR,DTREPLYCO ,103) AS COREPLYDATE,
							 CONVERT(VARCHAR,TARGETDATE ,103) AS TARGETDATE,
							 CONVERT(VARCHAR,DTOFPLACEMENTINPRESENTSCALE ,103) AS PLACEINPRESENTSCALEDATE,
							 CONVERT(VARCHAR,DTSANCTIONORDER ,103) AS SANCTIONORDERDATE,
							 CONVERT(VARCHAR,DT_ERCO ,103) AS ERCODATE,
							 CONVERT(VARCHAR,REF_CVC_2,103) AS CVC2REF,
							 CONVERT(VARCHAR,REC_CVC_2,103) AS RECCVC2,
							 CONVERT(VARCHAR,APPEAL,103) AS APPEAL,
							 CONVERT(VARCHAR,PRELIM_ENQ,103) AS PRELIMENQ,
							 CONVERT(VARCHAR,REGU_ENQ,103) AS REGUENQ,
							 CONVERT(VARCHAR,dtSANCTIONRECIVED,103) AS SANCTIONRECIVED,
							 CONVERT(VARCHAR,dtSANCTIONREFUSED,103) AS SANCTIONREFUSED,
							 CONVERT(VARCHAR,DT_SUB_REP,103) AS CSOREPDATE,
							 CONVERT(VARCHAR,A1C_CVC,103) AS A1CSCVC,
						     CONVERT(VARCHAR,A1E_CVC,103) AS A1EOPOCVC,
						     CONVERT(VARCHAR,A2_CVC,103) AS A2FOCVC,
									   
							 ([dbo].ReverseColumnValue_Function(STATUS,RNO,''VIG'')) AS SHORTSTATUS,
							  ADDUSER AS ENTRYBY,ISNULL(CONVERT(VARCHAR(50),ADDDATE,103),'''') AS ENTRYDATE,
							  ISNULL(MODUSER,'''') AS MODIFYBY,ISNULL(CONVERT(VARCHAR(50),MODDATE,103),'''') AS MODIFYDATE ,
							  NEWZONE AS NEWZONE,NEWCIRCLE AS NEWCIRCLE, TMSAC_REF AS TMSACREF,
							  CA.ApprovalStatus AS APPROVALSTATUS,
							  CASE CA.ApprovalStatus
								   WHEN ''P'' THEN ''Pending Approval''
								   WHEN ''A'' THEN ''Approved''
								   WHEN ''C'' THEN ''Changes Requested''
								   WHEN ''X'' THEN ''Rejected''
							  END AS APPROVALSTATUSTEXT,
							  ISNULL(CA.CheckerRemarks,'''') AS CHECKERREMARKS
					  FROM VIGILANCE V
						   LEFT JOIN CASE_APPROVAL CA ON CA.ModuleCode=''VIGILANCE'' AND CA.RecordCode=V.CODE
					  WHERE '+@STRCOND+'
					  ORDER BY V.ADDDATE DESC'
			EXEC(@SQL);
			PRINT(@SQL);
			PRINT(@ERRORCODE);
		END
		
	ELSE
		BEGIN	
			IF EXISTS (SELECT 1 FROM VIGILANCE WHERE (CASE WHEN @p_VIEW='GET' THEN RNO ELSE CAST(CODE AS VARCHAR) END)=@p_SEARCHNO AND ACTIVE='Y')
				BEGIN
					SELECT CODE,RNO,BRNAME AS BRCOMPLAINT,CIRCLEOFFICE AS CIRCLEOFFICE,RNO1 AS RNO1,
						   NAMEOFPARTICULARS AS NAMEOFPARTICULARS,BASICPAY,
						   NAME AS NAME,PFNUMBER AS PFNO,PRESENTPOSTING AS PRESENTPOSTING,
						   SOURCE AS SOURCE,REGISTER AS REGISTER,ACCTT_NAME AS ACCOUNTNAME,
						   AMOUNT AS AMOUNT,FINAL AS FINAL,DESIGNATION AS DESIGNATION,
						   PDREFNO_SUSPNO AS DREFNO,LAPSENATURE AS LAPSENATURE,REASONSFORINCLUSION AS REASONSFORINCLUSION,
						   DAREFNO AS DAREFNO,DELETIONREASON AS DELETIONREASONS,US AS US,
						   INVOFFICERNAME AS INVOFFICERNAME,RECOMMOFCVC AS RECOMMOFCVC,CBI_RC_NO1 AS CBIRCNO1,
						   IR_CBIPENDING AS IRCBIPENDING,RECOM_CBI AS CBIRECOM,POL_FIR_NO AS POLFIRNO,
						   RC_SOURCE AS RCSOURCE,INVESTIG AS INVESTIG,CVC_OM_NO AS CVCOMNO,
						   CVC_2_PROPOSED AS CVC2PROPOSED,ADV_1_AWAITED AS ADV1AWAITED,NATUREOFACCOUNT AS NATUREOFACCOUNT,
						   NAME_PO AS PONAME,PO_CBI AS POCBI,(CASE WHEN DTRNO IS NULL THEN 'N' ELSE 'Y' END) AS CHK_RNODATE,
				           DTS_HEAR AS DTSHEAR,PUNISHMENTPROPOSEDBY AS PUNISHMENTPROPOSEDBYDA,APPEAL AS APPEAL,
						   PENALTY AS PENALTY,DISP_AUTHORITY AS DISPAUTHORITY,DISAUTHORITYSCIRCLE AS DISAUTHORITYCIRCLE,
						   PREVCASE_PUNISHMENTS AS PREVCASEPUNISHMENT,ADVICECVOI AS CVOADVICE,NA_PUN_DA AS NAPUNDA,
						   LODINO AS LODINO,LODICASE AS LODICASE,CONNECTED_VIGCASE AS CONNECTEDVIGCASE,
						   FEILD1 AS FIELD1,DAPROPOSAL_2 AS DAPROPOSAL2,PENDING_2 AS PENDING2ND,
						   STATE AS STATE,NAT_CHSHEET AS NATCHSHEET,COMP_RE AS RECOM,
						   NO_AWARD_S AS NOAWARDS,PROPOSEDACTIONTOCVC AS PROPOSEDACTIONTOCVC,REG_INVOK AS REGINVOK,
						   CBI_RC_NO2 AS CBIRCNO2,NAME_EO AS EONAME,NAME_CDI AS CDINAME,
						   ADV_2_AWT AS ADV2AWT,STATUS_INBRIEF AS STATUSINBRIEF,LODINEW AS LODINEW,
						   EOCDI AS EOCDI,DAPROPOSAL AS DAPROPOSAL,ISTPENDING AS ISTPENDING,PENALTYTYPE,PENALTYPROCEEDING,
						   ADVICECVO2 AS CVO2ADVICE,CVCSADVICEII AS CVCADVICEII,STATUS,STATUSCODE,'' AS WRITTENBRIEFPO,
						   CBI_ZONE AS ZONE,SCALE,ISNULL(NATURECASE,0) AS NATURE,(CASE WHEN DATEOFCLOSURE IS NULL THEN 'N' ELSE 'Y' END) AS CLOSURE,
						   LODICODE,LODIINCLUSIONREASON,LODIDELETIONREASON,
						   
						   CONVERT(VARCHAR,DATEOFCOMPLAINT,103) AS RECDATECOMP,
						   CONVERT(VARCHAR,DTRNO ,103) AS RNODATE,
						   CONVERT(VARCHAR,DTCHARGE ,103) AS CHARGEDATE,
						   CONVERT(VARCHAR,DT_RC1 ,103) AS RC1DATE,
						   CONVERT(VARCHAR,DTOFRETIREMENT ,103) AS RETIREMENTDATE,
						   CONVERT(VARCHAR,DTOFSUSPENSION ,103) AS SUSPENSION,
						   CONVERT(VARCHAR,DTOFRECREPORT ,103) AS RECREPORTDATE,
						   CONVERT(VARCHAR,DTOCCUR ,103) AS OCCURDATE,
						   CONVERT(VARCHAR,DT_OM_CVC ,103) AS OMCVCDATE,
						   CONVERT(VARCHAR,DT_FIR ,103) AS FIRDATE,
						   CONVERT(VARCHAR,DT_APP_PO ,103) AS APPPODATE,
						   CONVERT(VARCHAR,DT_APP_EO ,103) AS APPEODATE,
						   CONVERT(VARCHAR,DTLASTRH,103) AS LASTRHDATE,
						   CONVERT(VARCHAR,DTFINAL ,103) AS FINALDATE,
						   CONVERT(VARCHAR,DT_CON_ENQ ,103) AS CONENQDATE,
						   CONVERT(VARCHAR,DTOFBASICPAY,103)AS BASICDATE,
						   CONVERT(VARCHAR,DT_APP_CDI ,103) AS APPCDIDATE,
						   CONVERT(VARCHAR,DT_CVO_ADVICE_2 ,103) AS CVO2ADVICEDATE,
						   CONVERT(VARCHAR,DTADVICESENTTODA ,103) AS ADVICESENTTODADATE,
						   CONVERT(VARCHAR,DTWRITTENBRIEFCo ,103) AS WRITTENBRIEFCODATE,
						   CONVERT(VARCHAR,DT_2ND_DA ,103) AS DA2NDDATE,
						   CONVERT(VARCHAR,DT_ORD_DA ,103) AS DAORDDATE,
						   CONVERT(VARCHAR,DT_REGULAT ,103) AS REGULATDATE,
						   CONVERT(VARCHAR,DT_IST_DA ,103) AS ISTDADATE,
						   CONVERT(VARCHAR,DTOFREVOCATION ,103) AS REVOCATIONDATE,
						   CONVERT(VARCHAR,REVIEWDATE ,103) AS REVIEWDATE,
						   CONVERT(VARCHAR,DATEOFCLOSURE ,103) AS CLOSUREDATE,
						   CONVERT(VARCHAR,DT_CVO_ADVICE ,103) AS CVOADVICEDATE,
						   CONVERT(VARCHAR,DTREFERTOCVC ,103) AS REFERTOCVCDATE,
						   CONVERT(VARCHAR,DT_RC2 ,103) AS RC2DATE,
						   CONVERT(VARCHAR,COMMITMENTDT ,103) AS COMMITMENTDATE,
						   CONVERT(VARCHAR,DTCHSHEETFILED ,103) AS CHSHEETFILEDDATE,
						   CONVERT(VARCHAR,DTREPLYCO ,103) AS COREPLYDATE,
						   CONVERT(VARCHAR,TARGETDATE ,103) AS TARGETDATE,
						   CONVERT(VARCHAR,DTOFPLACEMENTINPRESENTSCALE ,103) AS PLACEINPRESENTSCALEDATE,
						   CONVERT(VARCHAR,DTSANCTIONORDER ,103) AS SANCTIONORDERDATE,
						   CONVERT(VARCHAR,DT_ERCO,103) AS ERCODATE,
						   CONVERT(VARCHAR,REF_CVC_2,103) AS CVC2REF,
						   CONVERT(VARCHAR,REC_CVC_2,103) AS RECCVC2,
						   CONVERT(VARCHAR,APPEAL,103) AS APPEAL,
						   CONVERT(VARCHAR,PRELIM_ENQ,103) AS PRELIMENQ,
						   CONVERT(VARCHAR,REGU_ENQ,103) AS REGUENQ,
						   CONVERT(VARCHAR,dtSANCTIONRECIVED,103) AS SANCTIONRECIVED,
						   CONVERT(VARCHAR,dtSANCTIONREFUSED,103) AS SANCTIONREFUSED,
						   CONVERT(VARCHAR,DT_SUB_REP,103) AS CSOREPDATE,
						   CONVERT(VARCHAR,A1C_CVC,103) AS A1CSCVC,
						   CONVERT(VARCHAR,A1E_CVC,103) AS A1EOPOCVC,
						   CONVERT(VARCHAR,A2_CVC,103) AS A2FOCVC,
						   
						   ([dbo].ReverseColumnValue_Function(STATUS,RNO,'VIG')) AS SHORTSTATUS,
						   ADDUSER AS ENTRYBY,ISNULL(CONVERT(VARCHAR(50),ADDDATE,103),'') AS ENTRYDATE,
						   ISNULL(MODUSER,'') AS MODIFYBY,ISNULL(CONVERT(VARCHAR(50),MODDATE,103),'') AS MODIFYDATE,
						   DESK_USER_REMARKS,BANKNAME,
						   LETTERSENTTO,
						   ISNULL(CONVERT(VARCHAR(50),LETTERSENTDATE,103),'') AS LETTERSENTDATE,
						   ISNULL(CONVERT(VARCHAR(50),REMINDERDATE,103),'') AS REMINDERDATE,
						   ISNULL(CONVERT(VARCHAR(50),REPLYRECEIVEDDATE,103),'') AS REPLYRECEIVEDDATE,
						   NEWZONE AS NEWZONE,NEWCIRCLE AS NEWCIRCLE, TMSAC_REF AS TMSACREF,
						   CA.ApprovalStatus AS APPROVALSTATUS,
						   CASE CA.ApprovalStatus
								WHEN 'P' THEN 'Pending Approval'
								WHEN 'A' THEN 'Approved'
								WHEN 'C' THEN 'Changes Requested'
								WHEN 'X' THEN 'Rejected'
						   END AS APPROVALSTATUSTEXT,
						   ISNULL(CA.CheckerRemarks,'') AS CHECKERREMARKS
					FROM VIGILANCE V
						 LEFT JOIN CASE_APPROVAL CA ON CA.ModuleCode='VIGILANCE' AND CA.RecordCode=V.CODE
					WHERE V.ACTIVE='Y' AND (CASE WHEN @p_VIEW='GET' THEN V.RNO ELSE CAST(V.CODE AS VARCHAR) END)=@p_SEARCHNO
					ORDER BY V.RNO;
				END
			ELSE
				BEGIN
					SET @o_ERRCODE= -1;
					SET @o_EERMSG= @p_SEARCHNO + '- Vigilance Number does not Exists......!';
				END	
		END	
END
GO

-------------------------------------------------------------------------------------------------
-- 4. dbo.spVigilanceUser_Update  -- close the bulk-update bypass
--
--    This proc (Mis/frmVigilanceUpdate.aspx, MISUSER-only) changes Basic Pay, DA_CO/ZO/HO,
--    Register or Penalty Proceeding on an existing record. It never touched the approval
--    state, so a maker could alter an approved record and it stayed approved and
--    unverified. Now the change re-queues the record.
--
--    @p_USERROLE / @p_USERIP are appended with defaults so the existing call site, which
--    passes nine parameters, keeps working untouched.
-------------------------------------------------------------------------------------------------
CREATE OR ALTER PROC [dbo].[spVigilanceUser_Update]
(
	@p_RNO		VARCHAR(50),
	@p_DACOZOHO	VARCHAR(100),
	@p_BASICPAY	VARCHAR(100),
	@p_FIELD	VARCHAR(50),
	@p_REGISTER	VARCHAR(50),
	@p_PENALTYPROCEEDING BIGINT,
	@p_USER		VARCHAR(50),
	@o_EERMSG	VARCHAR(MAX) OUTPUT,
	@o_ERRCODE	INT OUTPUT,
	@p_USERROLE	VARCHAR(50)=NULL,
	@p_USERIP	VARCHAR(30)=NULL
)
AS
BEGIN
	DECLARE @CODE BIGINT, @OLDAPPROVALSTATUS CHAR(1);

	SET @o_ERRCODE=0;
	IF(@p_RNO <> '')
		BEGIN
			SELECT @CODE = CODE FROM VIGILANCE WHERE RNO=@p_RNO AND ACTIVE='Y';

			IF(@CODE IS NOT NULL)
				BEGIN
					IF(@p_FIELD <> 'SELECT')
						BEGIN
							SELECT @OLDAPPROVALSTATUS = ApprovalStatus
							FROM   CASE_APPROVAL
							WHERE  ModuleCode='VIGILANCE' AND RecordCode=@CODE;

							--A REJECTED RECORD IS NOT EDITABLE THROUGH ANY PATH.
							IF(@OLDAPPROVALSTATUS = 'X')
								BEGIN
									SET @o_ERRCODE=3;
									SET @o_EERMSG= 'This record has been rejected by the checker and cannot be edited......!';
									RETURN;
								END

						  BEGIN TRY
							BEGIN TRAN;

							--UPDATE TBALE VIGILANCE_HISTORY
							INSERT INTO VIGILANCE_HISTORY SELECT * FROM VIGILANCE WHERE RNO=@p_RNO;

							IF(@p_FIELD = 'BASICPAY')
								BEGIN
									UPDATE VIGILANCE SET BASICPAY=@p_BASICPAY,MODUSER=@p_USER,MODDATE=GETDATE() WHERE RNO=@p_RNO;
									SET @o_ERRCODE=1;
									SET @o_EERMSG= 'Basic Pay Updated Sucessfully......!';
								END

							ELSE IF(@p_FIELD = 'DA_CO_ZO_HO')
								BEGIN
									UPDATE VIGILANCE SET DISAUTHORITYSCIRCLE=@p_DACOZOHO,MODUSER=@p_USER,MODDATE=GETDATE() WHERE RNO=@p_RNO;
									SET @o_ERRCODE=1;
									SET @o_EERMSG= 'DA_CO/ZO/HO Updated Sucessfully......!';
								END

							ELSE IF(@p_FIELD = 'REGISTER')
								BEGIN
									UPDATE VIGILANCE SET REGISTER=@p_REGISTER,MODUSER=@p_USER,MODDATE=GETDATE() WHERE RNO=@p_RNO;
									SET @o_ERRCODE=1;
									SET @o_EERMSG= 'Register Updated Sucessfully......!';
								END

							ELSE IF(@p_FIELD = 'PENALTYPROCEEDING')
								BEGIN
									UPDATE VIGILANCE SET PENALTYPROCEEDING=@p_PENALTYPROCEEDING,MODUSER=@p_USER,MODDATE=GETDATE() WHERE RNO=@p_RNO;
									SET @o_ERRCODE=1;
									SET @o_EERMSG= 'Penalty Proceeding Updated Sucessfully......!';
								END

							--MAKER-CHECKER: THE EDIT INVALIDATES ANY EARLIER DECISION, SO SEND IT BACK
							--TO THE CHECKER RATHER THAN LEAVING IT APPROVED AND UNVERIFIED.
							IF(@o_ERRCODE = 1 AND @OLDAPPROVALSTATUS IN ('A','C'))
								BEGIN
									UPDATE CASE_APPROVAL
									   SET ApprovalStatus = 'P',
										   MakerUser      = @p_USER,
										   MakerDate      = GETDATE(),
										   CheckerUser    = NULL,
										   CheckerDate    = NULL,
										   CheckerRemarks = NULL
									 WHERE ModuleCode='VIGILANCE' AND RecordCode=@CODE;

									INSERT INTO CASE_APPROVAL_HISTORY
										(ModuleCode, RecordCode, ActionType, ActionBy, Remarks, UserRole, UserIP)
									VALUES
										('VIGILANCE', @CODE, 'RESUBMITTED', @p_USER,
										 @p_FIELD + ' changed via Vigilance Update screen.', @p_USERROLE, @p_USERIP);
								END

							COMMIT TRAN;
						  END TRY
						  BEGIN CATCH
							IF (XACT_STATE() <> 0) ROLLBACK TRAN;
							SET @o_ERRCODE=0;
							SET @o_EERMSG= 'Could not update the record: ' + ERROR_MESSAGE();
						  END CATCH
						END
				END
			ELSE
				BEGIN
					SET @o_ERRCODE=2;
					SET @o_EERMSG= 'Invalid Vigilance (R) Number......!';
				END
		END
END
GO
